### ISSUE TITLE
File association management - xdg-desktop

### ISSUE THREAD

**Issue by woodenshoe-wi** [woodenshoe-wi/rox-filer#2]
File association management is not xdg-desktop compliant.

https://github.com/puppylinux-woof-CE/woof-CE/pull/1513#issuecomment-514574491

**Comment by rizalmart** [comment]
I make a workaround in order to make rox-filer xdg-desktop compliant for now.

http://www.murga-linux.com/puppy/viewtopic.php?p=1037217&sid=4220a8479b0d09150098f13bff05a9bb#1037217

**Comment by rizalmart** [comment]
I noticed latest rox-filer modifications can read mimeinfo cache. However it does not read mimeapps.list and defaults.list file. Those files should be read first before mimeinfo.cache. mimeapps.list and defaults.list is a user defined file where the user's preferred program associated with file is saved unlike mimeinfo.cache which changes its content every add/remove packages and load/unload sfs modules

**Comment by woodenshoe-wi** [comment]
I am still following the conversation at woof-CE although I am no longer officially a member, so some of this is in response to comments there.

I am generally pretty busy from May through December and don’t have much time to work on computer stuff.  In addition I have been avoiding replacing the hard drive in my PC that I think is failing and just haven’t been using my PC...  at some point I will have to face the problem and fix my PC, but I hate it when hard drives fail and am avoiding it as long as I have other things more important to do.

Given these circumstances, if you or anyone else wants to work on ROX-Filer feel free to fork it and work in your own branch.  When the time would come that I was ready to do some more work on ROX-Filer I will merge or cherry pick whatever is appropriate (finished and in a working state).  The GitHub “Network graph” is great for seeing what changes others have been working on.

I had been working on enhancing the icon auto placement when my hard drive started acting up, at first I thought I had introduced a memory leak.  The partially tested code is available at https://github.com/woodenshoe-wi/rox-filer/tree/desktop-drive-icons if anyone is interested I also have the modified woof-CE scripts that I tested in the raspi build @wdlkmpx made.  It is a bit of a chicken and egg problem, the enhanced icon placement can’t be tested without changing the woof-CE scripts, but changing the woof-CE scripts would make it dependent on the untested version of ROX.

It would be nice if the “Shift-open” action could be configured separately from the default app used to open files.  For example, if clicking on a text file would open it in leafpad, but shift-clicking on it would open it in geany.  The same thing for image files, clicking on it would open it in an image viewing program, and shift-clicking would open it in an image editing program.

At some point I would like to see if it would be doable to get ROX-Filer working with GTK3 because of wayland support, but that is not going to happen any time soon.

**Comment by woodenshoe-wi** [comment]
There is a fork of ROX-Filer in the puppylinux-woof-CE organization now,  
https://github.com/puppylinux-woof-CE/rox-filer

 I think that wdlkmpx is working on the needed changes for xdg-desktop compliance, so I am closing this issue.
