### ISSUE TITLE
Roxfiler window no longer shows /mnt/home in title

### ISSUE THREAD

**Issue by rserwin1** [woodenshoe-wi/rox-filer#4]
In the Dpup stretch forum thread, WiZard asked:
"Is there a way to change rox's behavior ... to identify the home partition as: /mnt/home?"

Rox/roxfiler has shown the home partition as /mnt/home until recently...

Oops, I intended to submit this in the woof-CE project, so am moving it there.

**Comment by woodenshoe-wi** [comment]
I think this was actually a woof-CE issue, so I am closing this.
