### ISSUE TITLE
Get/SetOption RPC

### ISSUE THREAD

**Issue by jamesbond3142** [woodenshoe-wi/rox-filer#5]
I saw this commit on jun7's rox-filer: [Add RPC to read and set options](https://github.com/jun7/rox-filer/commit/d9dcb5b14301308facad41bc072f264b79346385). Since you're the author, I'd though I'd ask it here instead.

Can you help to elaborate what these new RPC are for, and when do you think they will be used? If you have discussed this elsewhere (e.g. in the Puppy forum), a link to the discussion would be good enough.

Thanks!

**Comment by woodenshoe-wi** [comment]
Funny that I didn’t get an email when you opened this issue, but now that you bring it to my attention I will answer it.

By itself it might not make sense, but it was originally part of the desktop-drive-icons branch.

I added **pinboard.c: Add Half-automatic placement** fa121d7,  
**pinboard.c: Half-automatic placement margin handling** 596c81b,  
and **pinboard.c: Make SEARCH_STEP configurable**, 65de57e. 
to be used with my modified versions of the frontend_rox_func and eventmanager scripts, woodenshoe-wi/woof-ce@bc76e3f

I needed the eventmanager script to be able to change the margin and SEARCH_STEP settings in ROX-Filer.

I don’t know why the RPC commit was merged without the other commits, or if my modified frontend_rox_func and eventmanager script are actually being used.

Since I have your attention, I noticed that the cross compiler that you used to compile most of the static programs for your ARM initrd made binaries that will run on a pi1/pi zero.  I was able to get “Bulldog Linux” to boot on my pi1 by using the Raspup kernel.

If I wanted to recompile just the non Xorg parts of Fatdog for pi zero are there any special instructions besides what I found at http://lightofdawn.org/wiki/wiki.cgi/-wiki/FatdogArm/NativeCompiler like would the Raspup kernel source version be OK as the kernel headers for the native compiler or should I use something else for the kernel headers?

**Comment by jamesbond3142** [comment]
> By itself it might not make sense, but it was originally part of the desktop-drive-icons branch.

> I needed the eventmanager script to be able to change the margin and SEARCH_STEP settings in ROX-Filer.

Ah ok, thanks for the reply. So it should be safe to revert that commit. I carry my own patch for drive icons; similar but not identical to yours (instead of mucking around with existing function I added a new RPC specifically to add drive icons and localise all my changes there).

> I noticed that the cross compiler that you used to compile most of the static programs for your ARM initrd made binaries that will run on a pi1/pi zero. I was able to get “Bulldog Linux” to boot on my pi1 by using the Raspup kernel.

Those were compiled using aboriginal linux 1.2.4 (gcc version 4.2.1) which outputs armv6l binaries - suitable for many ARM boards old and new. I don't think Rob keeps a copy of the older cross-compiler binaries. I'm happy to pass my copy if you need it.

> If I wanted to recompile just the non Xorg parts of Fatdog for pi zero are there any special instructions besides what I found at http://lightofdawn.org/wiki/wiki.cgi/-wiki/FatdogArm/NativeCompiler like would the Raspup kernel source version be OK as the kernel headers for the native compiler or should I use something else for the kernel headers?

So, do you just want to build packages using the existing native compiler? Or do you want to build a new native compiler? Or do you want to build packages using the cross-compiler?

If you're working with the "beta" release of FatdogArm, then the kernel headers I used with that, was the kernel headers for odroid, which came from linux-3.8. The thing with kernel headers are:
1. They get "baked-in" into the glibc when glibc is built; so once you have a working glibc, then never-ever change the kernel headers again.
2. It's okay to use older kernel headers with newer glibc. Older kernel headers means glibc will "emulate" some of the newer kernel functions, when you're running on the old kernel. If you run a newer kernel, glibc will just use it directly.

PS: I'm closing the case since you've answered my question but please feel free to continue the conversation.

**Comment by woodenshoe-wi** [comment]
The only binaries that I deleted from the initrd were according to the readme:  
 - losetup-klibc (from klibc 2.0.2, linaro 4.7-2013.4)
 - dash (from klibc 2.0.2, linaro 4.7-2013.4)
 - e3 (not mentioned in the readme, but x86-64)

I can reuse all the binaries compiled by the aboriginal compiler, so I don’t think I need it.  If the binaries that I deleted aren’t important, I figured I could use the initrd as is.

> So, do you just want to build packages using the existing native compiler?

Is there an existing native compiler for Fatdog that creates ARMv6 armhf binaries?

I thought that I would have to follow the instructions to make a new ARMv6 hard float native compiler.

Many years ago, I played around with Linux From Scratch so I am somewhat familiar with the process and like the way that they write the instructions.

I removed the existing kernel modules from the initrd and replaced them with the version 4.19.75+ kernel modules from the Raspup kernel that I am borrowing.

I don’t plan on using a kernel older than that, so I was wondering if it would be OK to “bake” that version into the new glibc or if it would be more useful to have an ARMv6 hard float glibc that can be used with older kernels.

The only ARM boards that I am familiar with are Raspberry Pis, so I don’t know if there are any other ARMv6 hard float boards that are using older kernels.

Now if there already is an ARMv6 hard float native compiler for Fatdog that I don’t know about I would use that.  I don’t want to redo what someone else has already done, but my Bulldog needs a save file and a devx. 😃

**Comment by jamesbond3142** [comment]
> e3 (not mentioned in the readme, but x86-64)

I have the ARM version of it, but I forgot to replace it in initrd.
Oh well, it has been years and you're the only one who notice it, so I think I won't bother updating FatdogArm's initrd anymore.

> Is there an existing native compiler for Fatdog that creates ARMv6 armhf binaries?

No, unfortunately. The existing native/cross-compiler can be persuaded to produce armv6-hf, but eventually the problem is glibc. Unless you want static programs throughout (using dietlibc or musl) you will have to rebuild glibc; and rebuilding glibc means you'll have to rebuild your native compiler.

> I thought that I would have to follow the instructions to make a new ARMv6 hard float native compiler.

Yes, you do. The CFLAGS should be "-marm -march=armv6 -mfpu=vfp -mfloat-abi=hard" or something like that.

Some of the warnings for renaming gnueabihf to gnueabi probably no longer applies, as newer gcc does understand gnueabihf.


> I removed the existing kernel modules from the initrd and replaced them with the version 4.19.75+ kernel modules from the Raspup kernel that I am borrowing.
> I don’t plan on using a kernel older than that, so I was wondering if it would be OK to “bake” that version into the new glibc or if it would be more useful to have an ARMv6 hard float glibc that can be used with older kernels.

That's really up to you. If 4.19 is the minimum kernel you want to use, the just use the headers from 4.19

> The only ARM boards that I am familiar with are Raspberry Pis, so I don’t know if there are any other ARMv6 hard float boards that are using older kernels.

I actually am not aware the Raspi1/0 ARMv6 comes with VFP support. I would consider that as a rarity :)

> Now if there already is an ARMv6 hard float native compiler for Fatdog that I don’t know about I would use that.

Unfortunately there isn't. But why you do want native compiler? Unless you're building stuff like vlc or browser ... most non-Xorg programs can be persuaded to build using a cross-compiler, and it would be faster too (I remember Mick telling me that Raspi1 is a very slow dog for even __running__ programs, let along compiling; and Barry wrote in the blog that the compilation process can run for hours).

If you're happy with this idea, you can use the existing cross-compiler (anyone of them - aboriginal, linaro, fatdog, etc) to build a new glibc and use it as the new "sysroot" and be done with it.

Or, if you're happy to use musl, you can use https://github.com/richfelker/musl-cross-make

But if you still insist on native compiler, alternative instructions exist (which didn't exist when I wrote my instructions then).

1. Install musl and build musl with march=armv6 as above, and the resulting musl libc will be armv6 compatible. You must do this on armv7 machines (Raspi2/3) but the resulting binaries should run on armv6. Musl is usually used for static libs but you __can__ have a dynamic linker too using it. I think this is the fastest route.

2. If you want to re-do the whole thing, then instead of my old instruction + LFS, you can use CLFS http://clfs.org/view/clfs-embedded/arm/
This one will build a musl-based system.

Both 1 & 2 results in musl-based system. If you want to use glibc-based system:

3. You'll need to use older CLFS: http://clfs.org/view/sysvinit/ - they don't have one for ARM but you can use any of them and replace the references to ARM.

4. Of course, you can use my original instructions - they'd probably need to be tweaked for newer gcc/glibc, though.

**Comment by woodenshoe-wi** [comment]
Thanks for the information!

After reading your info, I thought of one more option to get a native compiler and glibc.

Puppy uses the parent distro’s packages for gcc/glibc, and the Raspbian gcc/glibc is pretty much what I wanted to duplicate.

It wouldn’t be a pure LFS Fatdog anymore, but I could start by trying to duplicate the Fatdog ARM devx using Raspbian debs.

I figured having a native compiler would make it easier to install small programs by downloading the source code, ./configure, make, make install and you’re done.  But you might want to find something else to do during the process... 😃  One thing I remember from LFS was that even ./configure can take a really long time...  I guess it is more of a trade off between time and convenience/simplicity.
